spring:
  application:
    name: Junction-Dino

  datasource:
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://db:5432/main
    username: postgres
    password: 1234

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  security:
    user:
      name: user
      password: 1234

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

server:
  port: 8080
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: never     # Response 에 Stack Trace 를 표시할지 (never | always | on_param)
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

jwt:
  secret: HELLONICETOSEEYOUWELCOMETOTHEMYMATCHINGHELLONICETOSEEYOUWELCOMETOTHEMYMATCHINGHELLONICETOSEEYOUWELCOMETOTHEMYMATCHINGHELLONICETOSEEYOUWELCOMETOTHEMYMATCHING
  access-token-time: 864000000  # 10일
  refresh-token-time: 864000000  # 10일

logging:
  level:
    org:
      springframework:
        web:
          filter: DEBUG
        security:
          web:
            FilterChainProxy: DEBUG # or TRACE
            authentication: DEBUG
            access: DEBUG


